name: Deploy static website to Azure

on:
  push:
    branches:
      - main  # Ensure this matches your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"          # Since index.html is directly in the root folder, set this to "/"
          output_location: "/"       # If you don't have a build output folder, keep this as "/"
